### ISSUE TITLE
xcowsay-utils -a not working

### ISSUE THREAD

**Issue by lastab** [haude/xcowsay-utils#3]
When I add -a option it shows error:
`cat: /tmp/xcowsay-utils: No such file or directory`
![selection_005](https://cloud.githubusercontent.com/assets/3922238/22649510/566140f8-eca3-11e6-970a-f857a5c9cf10.png)

**Comment by rhoit** [comment]
only work when xcowsay-utils has already ran once before.

**Comment by lastab** [comment]
I tried that too.
![selection_008](https://cloud.githubusercontent.com/assets/3922238/22829573/58db1806-efcb-11e6-8656-0f17a633651b.png)

**Comment by rhoit** [comment]
![screenshot116](https://cloud.githubusercontent.com/assets/1684754/22835571/5a9cdd3a-efe1-11e6-8842-88fc72bd8300.png)
